"""server.properties 编辑服务"""
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from core.io_atomic import atomic_write_text
from core.types import LogCallback


def _default_log(msg: str, lvl: str = "INFO") -> None:
    pass


DEFAULT_SERVER_PROPERTIES: Dict[str, str] = {
    "level-name": "world",
    "gamemode": "survival",
    "difficulty": "easy",
    "max-players": "20",
    "online-mode": "true",
    "pvp": "true",
    "allow-flight": "false",
    "enable-command-block": "false",
    "motd": "A Minecraft Server",
    "server-port": "25565",
    "view-distance": "10",
    "simulation-distance": "10",
    "white-list": "false",
    "spawn-protection": "16",
}


PROPERTY_DESCRIPTIONS: Dict[str, str] = {
    "level-name": "存档文件夹名称",
    "gamemode": "默认游戏模式",
    "difficulty": "默认难度",
    "max-players": "最大玩家数",
    "online-mode": "是否启用正版验证",
    "pvp": "是否允许玩家对战",
    "allow-flight": "是否允许飞行",
    "enable-command-block": "是否启用命令方块",
    "motd": "服务器列表中显示的描述",
    "server-port": "服务器端口",
    "view-distance": "视距",
    "simulation-distance": "模拟距离",
    "white-list": "是否启用白名单",
    "spawn-protection": "出生点保护半径",
}

BOOLEAN_PROPERTIES = {
    "online-mode",
    "pvp",
    "allow-flight",
    "enable-command-block",
    "white-list"}
INTEGER_RANGES: Dict[str, Tuple[int, int]] = {
    "max-players": (1, 100000),
    "server-port": (1, 65535),
    "view-distance": (2, 32),
    "simulation-distance": (2, 32),
    "spawn-protection": (0, 100000),
}
ENUM_PROPERTIES: Dict[str, Tuple[str, ...]] = {
    "gamemode": ("survival", "creative", "adventure", "spectator"),
    "difficulty": ("peaceful", "easy", "normal", "hard"),
}


class ServerPropertiesService:
    """读取、校验并原子写入 ``server.properties``。

    路径可传世界目录或文件本身；缺省键与 ``DEFAULT_SERVER_PROPERTIES`` 合并。
    不持有路径状态，每次调用显式传入。
    """

    def __init__(self, log: Optional[LogCallback] = None) -> None:
        """注入可选日志回调。

        Args:
            log: ``(message, level)`` 日志；缺省为 no-op。
        """
        self.log: LogCallback = log or _default_log

    def load(self, path: Path) -> Dict[str, str]:
        """加载 server.properties 并与默认值合并。

        Args:
            path: 世界目录或 ``server.properties`` 文件路径。

        Returns:
            完整属性字典；文件不存在时返回默认副本。
        """
        props_path = self._resolve_path(path)
        if not props_path.exists():
            return DEFAULT_SERVER_PROPERTIES.copy()
        props: Dict[str, str] = {}
        for line in props_path.read_text(
                encoding="utf-8",
                errors="replace").splitlines():
            raw = line.strip()
            if not raw or raw.startswith("#") or "=" not in raw:
                continue
            key, value = raw.split("=", 1)
            props[key.strip()] = value.strip()
        merged = DEFAULT_SERVER_PROPERTIES.copy()
        merged.update(props)
        return merged

    def save(self, path: Path, props: Dict[str, str]) -> None:
        """校验后原子写入 server.properties。

        Args:
            path: 世界目录或目标文件路径。
            props: 待写入的键值（字符串）。

        Raises:
            ValueError: 路径为空或校验失败。
        """
        if not str(path).strip():
            raise ValueError("保存位置不能为空")
        props_path = self._resolve_path(path)
        errors = self.validate(props)
        if errors:
            raise ValueError("; ".join(errors))
        props_path.parent.mkdir(parents=True, exist_ok=True)
        keys = list(DEFAULT_SERVER_PROPERTIES.keys())
        for key in props:
            if key not in keys:
                keys.append(key)
        lines = ["#Minecraft server properties", "#Generated by MCSaveHelper"]
        for key in keys:
            lines.append(f"{key}={props.get(key, '')}")
        atomic_write_text(props_path, "\n".join(lines) + "\n")
        self.log(f"已保存 server.properties: {props_path}", "CONFIG")

    def _resolve_path(self, path: Path) -> Path:
        if path.name == "server.properties":
            return path
        return path / "server.properties"

    def validate(self, props: Dict[str, str]) -> List[str]:
        """校验布尔、整数范围与枚举字段。

        Args:
            props: 待校验属性字典。

        Returns:
            人类可读错误列表；空列表表示通过。
        """
        errors: List[str] = []
        for key in BOOLEAN_PROPERTIES:
            value = props.get(key, "").lower()
            if value not in {"true", "false"}:
                errors.append(f"{key} 必须为 true/false")
        for key, (min_value, max_value) in INTEGER_RANGES.items():
            raw = props.get(key, "")
            try:
                int_value = int(raw)
            except ValueError:
                errors.append(f"{key} 必须为整数")
                continue
            if not min_value <= int_value <= max_value:
                errors.append(f"{key} 范围应为 {min_value}-{max_value}")
        for key, values in ENUM_PROPERTIES.items():
            if props.get(key) not in values:
                errors.append(f"{key} 必须为: {', '.join(values)}")
        return errors


def get_server_properties_service(
        log: Optional[LogCallback] = None) -> ServerPropertiesService:
    """创建绑定到单个编辑视图的 server.properties 服务实例。

    Args:
        log: 可选日志回调。

    Returns:
        新的 ``ServerPropertiesService``（非单例）。
    """
    return ServerPropertiesService(log=log)
