"""server.properties 编辑服务"""
from pathlib import Path
import os
import tempfile
from typing import Dict, List, Optional, Tuple

from core.types import LogCallback


def _default_log(msg: str, lvl: str = "INFO") -> None:
    pass


DEFAULT_SERVER_PROPERTIES: Dict[str, str] = {
    "level-name": "world",
    "gamemode": "survival",
    "difficulty": "easy",
    "max-players": "20",
    "online-mode": "true",
    "pvp": "true",
    "allow-flight": "false",
    "enable-command-block": "false",
    "motd": "A Minecraft Server",
    "server-port": "25565",
    "view-distance": "10",
    "simulation-distance": "10",
    "white-list": "false",
    "spawn-protection": "16",
}


PROPERTY_DESCRIPTIONS: Dict[str, str] = {
    "level-name": "存档文件夹名称",
    "gamemode": "默认游戏模式",
    "difficulty": "默认难度",
    "max-players": "最大玩家数",
    "online-mode": "是否启用正版验证",
    "pvp": "是否允许玩家对战",
    "allow-flight": "是否允许飞行",
    "enable-command-block": "是否启用命令方块",
    "motd": "服务器列表中显示的描述",
    "server-port": "服务器端口",
    "view-distance": "视距",
    "simulation-distance": "模拟距离",
    "white-list": "是否启用白名单",
    "spawn-protection": "出生点保护半径",
}

BOOLEAN_PROPERTIES = {
    "online-mode",
    "pvp",
    "allow-flight",
    "enable-command-block",
    "white-list"}
INTEGER_RANGES: Dict[str, Tuple[int, int]] = {
    "max-players": (1, 100000),
    "server-port": (1, 65535),
    "view-distance": (2, 32),
    "simulation-distance": (2, 32),
    "spawn-protection": (0, 100000),
}
ENUM_PROPERTIES: Dict[str, Tuple[str, ...]] = {
    "gamemode": ("survival", "creative", "adventure", "spectator"),
    "difficulty": ("peaceful", "easy", "normal", "hard"),
}


class ServerPropertiesService:
    def __init__(self, log: Optional[LogCallback] = None) -> None:
        self.log: LogCallback = log or _default_log

    def load(self, path: Path) -> Dict[str, str]:
        props_path = self._resolve_path(path)
        if not props_path.exists():
            return DEFAULT_SERVER_PROPERTIES.copy()
        props: Dict[str, str] = {}
        for line in props_path.read_text(
                encoding="utf-8",
                errors="replace").splitlines():
            raw = line.strip()
            if not raw or raw.startswith("#") or "=" not in raw:
                continue
            key, value = raw.split("=", 1)
            props[key.strip()] = value.strip()
        merged = DEFAULT_SERVER_PROPERTIES.copy()
        merged.update(props)
        return merged

    def save(self, path: Path, props: Dict[str, str]) -> None:
        if not str(path).strip():
            raise ValueError("保存位置不能为空")
        props_path = self._resolve_path(path)
        errors = self.validate(props)
        if errors:
            raise ValueError("; ".join(errors))
        props_path.parent.mkdir(parents=True, exist_ok=True)
        keys = list(DEFAULT_SERVER_PROPERTIES.keys())
        for key in props:
            if key not in keys:
                keys.append(key)
        lines = ["#Minecraft server properties", "#Generated by MCSaveHelper"]
        for key in keys:
            lines.append(f"{key}={props.get(key, '')}")
        fd, temp_name = tempfile.mkstemp(
            prefix=f".{props_path.name}.", suffix=".tmp", dir=props_path.parent
        )
        temp_path = Path(temp_name)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as output:
                output.write("\n".join(lines) + "\n")
                output.flush()
                os.fsync(output.fileno())
            os.replace(temp_path, props_path)
        finally:
            temp_path.unlink(missing_ok=True)
        self.log(f"已保存 server.properties: {props_path}", "CONFIG")

    def _resolve_path(self, path: Path) -> Path:
        if path.name == "server.properties":
            return path
        return path / "server.properties"

    def validate(self, props: Dict[str, str]) -> List[str]:
        errors: List[str] = []
        for key in BOOLEAN_PROPERTIES:
            value = props.get(key, "").lower()
            if value not in {"true", "false"}:
                errors.append(f"{key} 必须为 true/false")
        for key, (min_value, max_value) in INTEGER_RANGES.items():
            raw = props.get(key, "")
            try:
                int_value = int(raw)
            except ValueError:
                errors.append(f"{key} 必须为整数")
                continue
            if not min_value <= int_value <= max_value:
                errors.append(f"{key} 范围应为 {min_value}-{max_value}")
        for key, values in ENUM_PROPERTIES.items():
            if props.get(key) not in values:
                errors.append(f"{key} 必须为: {', '.join(values)}")
        return errors


def get_server_properties_service(
        log: Optional[LogCallback] = None) -> ServerPropertiesService:
    """Return a server-properties service scoped to one editor view."""
    return ServerPropertiesService(log=log)
