"""MCA on-disk constants (Anvil region format)."""
from __future__ import annotations

CHUNKS_PER_SIDE = 32
CHUNKS_PER_REGION = CHUNKS_PER_SIDE * CHUNKS_PER_SIDE

SECTOR_SIZE = 4096
LOCATION_TABLE_SIZE = SECTOR_SIZE
TIMESTAMP_TABLE_SIZE = SECTOR_SIZE
HEADER_SIZE = LOCATION_TABLE_SIZE + TIMESTAMP_TABLE_SIZE

COMPRESSION_GZIP = 1
COMPRESSION_ZLIB = 2
COMPRESSION_NONE = 3
COMPRESSION_LZ4 = 4

LENGTH_HEADER_SIZE = 4
COMPRESSION_HEADER_SIZE = 1
